README.md
Add some information to README file and will keep updating it with more info.
=> add information to README.md

README.rst
Updated the README file following rst standard.
The restructuredText is also using lightweight language that emphasize plain-text readability and is easy to define.
Besides, the restructuredText is specifically designed for writing technical documentation, which will be helpful when we want to enrich our README file.
=> update README file as rst format

virtwho/logger.py
Define the logger handler for project using.
=> add logger.py

virtwho/ssh.py
Define the paramiko ssh/sftp for project using.
=> add ssh.py

virtwho/settings.py
Define the Configure class to parse any INI file in local or remote server.
- Get option's value 
- Add option
- Update option
- Delete option
- Delete file
=> add settings.py

virtwho/ssh.py
It needs double (( )) in```transport = paramiko.Transport((self.host, self.port))```
=> code problem in ssh.py

virtwho.ini.sample
update ```host``` to ```server``` for ```[virtwho]``` section to make uniform.
add ```port```option for ```[local]``` section
=> options update for virtwho.ini.sample

virtwho/__init__.py
Define logger in init file for common using in most of files.
Define ```class FailException(BaseException)``` in init file to interrupt program and raise error.
=> move logger to init file and define FailException() class here

virtwho/register.py
The RHSMAPI class is used to check/get/delete consumers,  attach/remove subscription, and check the host-to-guest associations on rhsm server.
```
rhsm = RHSMAPI(host=, username=, password=, port=)
rhsm.get(hostname')
rhsm.delete(hostname=)
rhsm.pool(sku_id=)
rhsm.attach(host_name=, pool=)
rhsm.unattach(host_name=, pool=)
rhsm.associate(host_name=, guest_uuid=)
```
=> Define RHSMAPI for register.py

virtwho.ini.sample
```
[ahv]
server=
username=
password=
uuid=
hostname=
version=
cpu=
cluster=
guest_name=
guest_ip=
guest_username=
guest_password=
guest_uuid=
guest_state=
```
=> Add [ahv] section to virtwho.ini.sample

virtwho/register.py
Add public functions of request_get/post/delete used for rhsm/satellite api.
```
def request_get(url, auth, verify=False):
res = requests.get(url=url, auth=auth, verify=verify)
return res.status_code, res.json()
def request_post(url, auth, params, verify=False):
res = requests.post(url=url, auth=auth, params=params, verify=verify)
return res.status_code
def request_delete(url, auth, verify=False):
res = requests.delete(url=url, auth=auth, verify=verify)
return res.status_code
```
=> Add request_get/post/delete public functions

utils/docker.py
docker.py is used to create rhel container by docker and defined as a public tool.
Below is an examples to run with required arguments.
```# python3 docker.py --rhel-compose=RHEL-8.6.0-20220111.0 --docker-server=10.73.3.99 --docker-username=root --docker-password=password --container-name=test --container-port=33333 --container-username=root --container-password=password```
=> Define utils/docker.py

tests/conftest.py, tests/function/test_cli.py, utils/ini2json.py, virtwho/configure.py, virtwho/provision/virtwho_host.py, virtwho/provision/virtwho_properties.py, virtwho/register.py, virtwho/runner.py
Define the test_cli.py, this pr only contain below 4 test cases and used to review/discuss the docstring definition.
- test_debug
- test_oneshot
- test_interval
- test_print
Will keep to define new test cases for this file.
=> Define tests/function/test_cli.py

virtwho/configure.py
Create temp directory if not exist, ortherwise the runtest will fail.
=> Create temp directory if not exist

virtwho/provision/virtwho_host.py
Update the `job.mode` to `job.hypervisor` because have changed the option name in virtwho.ini
=> Update the job.mode to job.hypervisor

virtwho/provision/virtwho_host.py
Update the beaker_host with default value `%hp-z220%`
=> Update the beaker_host with default value

pytest.ini, tests/function/test_base.py, tests/function/test_cli.py, tests/function/test_config.py, tests/hypervisor/test_ahv.py, tests/hypervisor/test_esx.py, tests/hypervisor/test_hyperv.py, tests/hypervisor/test_kubevirt.py, tests/hypervisor/test_libvirt.py, tests/hypervisor/test_local.py, tests/hypervisor/test_rhevm.py, tests/hypervisor/test_xen.py, tests/subscription/test_rhsm.py, tests/subscription/test_satellite.py
Define demo cases in test files to debug the jenkins job.
Most of the cases will only print some messages.
=> Define demo cases in test files to debug the jenkins job

pytest.ini, tests/function/test_config.py, tests/function/test_multi_hypervisor.py, tests/function/test_pkg_info.py
Add two test files
- Add test_pkg_info.py 
- test_multi_hypervisor.py
=> Add test_pkg_info.py and test_multi_hypervisor.py

virtwho/provision/virtwho_host.py, virtwho/settings.py
The `virtwho_host.py` should be able to configure as the different hypervisors' requirements, so make this changing.
=> Debug virt-who host setting issue

tests-polarion-testcase-import/conftest.py, tests-polarion-testcase-import/function/test_cli.py, tests-polarion-testcase-import/gating/test_gating.py, tests-polarion-testcase-import/test_local_debug.py, utils/polarion_testcase_upload.py
This file is temporarily used to import the testcases to polarion because we defined bad format test cases in tests/ directory for the jenkins job debugging.
Will delete this file when the cases in /tests are available to use.
=> new add directory add tests-polarion-testcase-import/

tests/function/test_config.py
```
(env) [hkx303@kuhuang function]$ pytest test_config.py 
collected 4 items                                                                            
test_config.py ....                                                                    [100%]
=============================== 4 passed in 357.97s (0:05:57) ================================
```
=> Add 3 new cases in test_config.py

docs/virtwho_help_page_rhel_8, docs/virtwho_help_page_rhel_9, docs/virtwho_man_page_rhel_8, docs/virtwho_man_page_rhel_9, tests/package/test_info.py, virtwho/__init__.py, virtwho/base.py, virtwho/settings.py
```
======================== test session starts ==========================
collected 5 items                                                                                                                                
tests/package/test_info.py::TestVirtwhoPackageInfo::test_shipped_in_supported_arch PASSED      [ 20%]
tests/package/test_info.py::TestVirtwhoPackageInfo::test_version PASSED                      [ 40%]
tests/package/test_info.py::TestVirtwhoPackageInfo::test_man_page PASSED                  [ 60%]
tests/package/test_info.py::TestVirtwhoPackageInfo::test_help_page PASSED                   [ 80%]
tests/package/test_info.py::TestVirtwhoPackageInfo::test_packa …
```
=> Define test_info.py

virtwho/runner.py
- Add parameters `status= and jsn=` to support test hypervisor and entitlement server status by `#virt-who -s -j`
- Add function `status()` to analyze the output to a dictinary.
Got below dictionary by the function `status()`
```
{'virtwho-esx': {'source': {'connection': 'https://10.73.213.119', 'status': 'success', 'last_successful_retrieve': None, 'hypervisors': None, 'guests': None}, 'destination': {'connection': 'subscription.rhsm.stage.redhat.com', 'status': 'success', 'last_successful_send': None, 'last_successful_send_job_status': None}}}
```
=> Add -s -j option for run_cli()

virtwho/base.py
Define more functions to base.py
=> Define more functions to base.py

tests/package/test_install_uninstall.py
```
======================== test session starts ========================
collected 2 items                                                                                                                                
tests/package/test_install_uninstall.py::TestInstallUninstall::test_install_uninstall_by_yum PASSED   [ 50%]
tests/package/test_install_uninstall.py::TestInstallUninstall::test_install_uninstall_by_rpm PASSED   [100%]
```
=> Define test_install_uninstall.py

tests/package/test_upgrade_downgrade.py
```
======================== test session starts ========================
collected 2 items                                                                                                                                
tests/package/test_upgrade_downgrade.py::TestUpgradeDowngrade::test_upgrade_downgrade_by_yum PASSED   [ 50%]
tests/package/test_upgrade_downgrade.py::TestUpgradeDowngrade::test_upgrade_downgrade_by_rpm PASSED    [100%]
=========================== 2 passed in 249.47s (0:04:09) ===================
```
=> define the test_upgrade_downgrade.py

tests/conftest.py, tests/smoke/test_smoke.py, virtwho/configure.py, virtwho/register.py
```
================ test session starts ========================
collected 3 items                                                                                                                                
tests/smoke/test_smoke.py::TestSmoke::test_rhsm_proxy PASSED             [ 33%]
tests/smoke/test_smoke.py::TestSmoke::test_host_guest_association PASSED       [ 66%]
tests/smoke/test_smoke.py::TestSmoke::test_rhsm_options PASSED       [100%]
====================== 3 passed, 1 warning in 388.04s (0:06:28) ============
```
=> Define test_smoke.py with cases host_guest_association, rhsm_options and rhsm_proxy

tests/conftest.py, tests/function/test_config.py
This PR deponds on #70 , mark it draft PR
Test Result
All passed locally
=> Add configs, owner, hypervisor_id, http_proxy virtwho_conf cases

tests/conftest.py, tests/function/test_config.py, virtwho/configure.py
**Descritption**
- Functions
-  Added the sysconfig related cases
All test cases passed locally
=> Add sysconfig related functions and cases

utils/satellite.py, virtwho/provision/virtwho_satellite.py
=> Support sat6.12 for smoke testing and support the satellite for the new installation

tests/hypervisor/test_hypervisors_env.py, virtwho/provision/virtwho_hypervisor.py
Mainly for a patent research and demo.
Only developed on libvirt mode.
=> update virtwho_hypervisor.py, new define test_hypervisors_env.py

tests/conftest.py, tests/function/test_cli.py, tests/function/test_config.py, tests/function/test_service.py, tests/gating/test_gating.py, tests/package/test_upgrade_downgrade.py, tests/sca/test_sca.py, tests/smoke/test_smoke.py
Planning to combine the `hypervisor()` and `hypervisor_create(hypervisor)` to the one `hypervisor()`, and change the scope of  `hypervisor()` to class.
=> Update the fixture of hypervisor in conftest.py

tests/conftest.py, tests/hypervisor/conftest.py, tests/hypervisor/test_esx.py, virtwho/configure.py
Add the following cases for the esx mode:
All case passed locally
=> Add test_type, test_server, test_username, test_password and test_hypervisor_id cases to test_esx.py

tests/hypervisor/test_esx.py
Add test cases:
All passed locally
=> Add filter_and_exclude_hosts related case for esx hypervisor

tests/hypervisor/test_esx.py, virtwho/base.py
**Decscription**
positive:
negative:
All passed locally
=> Add filter_host_parents and exclude_host_parents related cases

tests/conftest.py
=> update the hypervisor_data to support libvirt-local mode

utils/parse_ci_message.py
=> fix pkg_url getting issue from CI_MESSAGE

virtwho/provision/virtwho_host.py
add `yum install -y expect net-tools` to the init host step
=> Virtwho host

utils/satellite.py, virtwho/provision/virtwho_satellite.py
=> support to deploy satellite6.12

tests/conftest.py, virtwho/base.py, virtwho/provision/virtwho_host.py
- support the solid host for gating test
- support to define compose path
=> virtwho_host: support the stable hosts for gating test

utils/__init__.py, utils/docker.py, utils/properties_update.py
Got the failure `ModuleNotFoundError: No module named 'utils'` in Jenkins job, so change to not import from utils.
=> utils: debug the sys.path import issue

utils/beaker.py, utils/docker.py, utils/ini2json.py, utils/kickstart.py, utils/parse_ci_message.py, utils/parse_test_result.py, utils/polarion_testcase_upload.py, utils/properties_update.py, utils/satellite.py, virtwho/provision/virtwho_host.py, virtwho/provision/virtwho_hypervisor.py, virtwho/provision/virtwho_satellite.py
always get the failure of `ModuleNotFoundError: No module named 'virtwho'` when run jenkins job, so change back to the origin.
=> utils: debug sys.path import issue

.flake8
=> Ignore the error E402 for flake8

tests/package/test_info.py, tests/package/test_install_uninstall.py, tests/package/test_upgrade_downgrade.py
always failed to upload new test cases to polarion with error `ERROR ImportTestcaseThread_5623 - Custom field 'upstream' not recognized.` 
so remove the custom filed to debug the issue.
=> docstring: debug the upstream filed issue

tests/function/test_cli.py, tests/function/test_config.py, tests/function/test_service.py, tests/gating/test_gating.py, tests/hypervisor/test_ahv.py, tests/hypervisor/test_default.py, tests/hypervisor/test_esx.py, tests/hypervisor/test_hyperv.py, tests/hypervisor/test_hypervisors_state.py, tests/hypervisor/test_kubevirt.py, tests/hypervisor/test_libvirt.py, tests/hypervisor/test_local.py, tests/hypervisor/test_multi_hypervisors.py, tests/hypervisor/test_rhevm.py, tests/hypervisor/test_xen.py, tests/package/test_info.py, tests/package/test_install_uninstall.py, tests/package/test_upgrade_downgrade.py, tests/sca/test_sca.py, tests/smoke/test_smoke.py, tests/subscription/test_rhsm.py, tests/subscription/test_rhsm_option.py, tests/subscription/test_satellite.py
1. add `subsystemteam` and `caselevel` fields
2. Update the docstring for [tests/hypervisor/test_default.py](https://github.com/VirtwhoQE/virtwho-test/compare/main...hkx303:virtwho-test:update_doc_string?expand=1#diff-8c5fbdd00fb457cba1e5f5b81811a9d8d325693f86ec906645a5f0e9dfd7b28b)
=> Update the docstring: add subsystemteam and caselevel

utils/polarion_testcase_upload.py
=> Add hyperlink field to xml file

tests/package/test_info.py, tests/package/test_upgrade_downgrade.py, utils/polarion_testcase_upload.py
=> utils/polarion_testcase_upload.py: correct the xml format to match the requirement of polarion

utils/polarion_testrun_import.py
=> utils/polarion_testrun_import.py: debug unsupported characters in xml file

tests/hypervisor/test_ahv.py, tests/hypervisor/test_default.py, tests/hypervisor/test_esx.py, tests/package/test_info.py, tests/subscription/test_rhsm.py, tests/subscription/test_satellite.py
Found some tese cases have the same title, need to update the docstring.
=> Update the docstring for polarion uploading

tests/function/test_cli.py, tests/function/test_config.py, tests/function/test_service.py, tests/gating/test_gating.py, tests/hypervisor/test_ahv.py, tests/hypervisor/test_default.py, tests/hypervisor/test_esx.py, tests/hypervisor/test_hyperv.py, tests/hypervisor/test_kubevirt.py, tests/hypervisor/test_libvirt.py, tests/hypervisor/test_local.py, tests/hypervisor/test_rhevm.py, tests/hypervisor/test_xen.py, tests/package/test_info.py, tests/package/test_install_uninstall.py, tests/package/test_upgrade_downgrade.py, tests/subscription/test_rhsm.py, tests/subscription/test_rhsm_option.py, tests/subscription/test_satellite.py, utils/libvirt_bridge_setup.sh, virtwho/provision/virtwho_host.py
=> virtwho_host.py to support configure local mode

tests/function/test_service.py, tests/hypervisor/test_default.py, tests/hypervisor/test_libvirt.py, tests/hypervisor/test_multi_hypervisors.py
=> update docstring again due to case id conflict

virtwho/provision/virtwho_host.py
Changed to use the server ip to replace hostname for local mode, which supports to get the host gateway.
Have debugged locally from deploying host from beaker and then install vm for local mode.
=> virtwho_host.py: change to use the server ip for local mode

tests/hypervisor/test_esx.py, tests/hypervisor/test_hyperv.py, tests/hypervisor/test_libvirt.py
=> Remove redundant cases for hypervisors

tests/hypervisor/conftest.py, tests/hypervisor/test_xen.py
=> Add test cases to test_xen.py

virtwho/provision/virtwho_host.py
Before we test the gating stable host only by ping the host, which is not so clever, so changed to test the ssh connection.
=> virtwho_host.py: perfect to define the gating stable server

virtwho/configure.py, virtwho/register.py, virtwho/ssh.py
$As subject, we need more debug info for the analyzation
=> Add the ssh and API log debug info

virtwho/provision/virtwho_hypervisor.py
Add a check in kubevirt guest.
=> Add kubevirt guest post

tests/upgrade/test_upgrade.py
Add the pre-upgrade test cases for virt-who 
```
[hkx303@kuhuang virtwho-test]$ pytest tests/upgrade/test_upgrade.py -k test_pre_upgrade -s
============== 1 passed, 1 deselected, 9 warnings in 169.38s (0:02:49) ===============
```
=> Add the pre-upgrade test cases for virt-who

tests/upgrade/test_upgrade.py
Add the post-upgrade test cases for virt-who
```
[hkx303@kuhuang virtwho-test]$ pytest tests/upgrade/test_upgrade.py -k test_post_upgrade -s
============== 1 passed, 1 deselected, 9 warnings in 169.38s (0:02:49) ===============
```
=> Add the post-upgrade test cases for virt-who

requirements.txt
To save time when build Jenkins job, change to install most of the required packages to the docker slave image by Dockerfile.
=> requirement.txt: packages installed to slave image.

utils/polarion_testcase_upload.py
Update the `total_case=` and `failed_case=` numbers to virtwho.ini, which data will be called by pipeline to send reminder email about if there is/are new cases uploaded by comparing with the old data.
=> polarion_testcase_upload.py: record the result to virtwho.ini

virtwho/base.py
The ctc builds are now happening outside of the beta folder.
=> rhel 10 beta is over

tests/function/test_config.py
Card-ID: CCT-1215
- removed assert for 'Connection made' in log for proxy connection
- added skip for sysconfig tests fo RHEL9, RHEL10
- updated assertations
=> fix for function tests

tests/function/test_config.py
Card-ID: CCT-1225
There are assertations that fail.  They are known and issues are filed for those cases.
I've put assertations into case statement - ie. They are skipped with log.info note.
=>  skipped assertations with note about openned issue
