README.rst

Added below introduction about properties.ini.sample to README file
```
properties.ini.sample is provided as a sample to define attributes
- Change the file name to properties.ini
- Update the necessary datas based on test requirements
- hypervisor-builder can help to get part of the information
```

Update README file to introduce properties.ini.sample

---

virtwho.ini.sample

Need the ssh_username and password to access satellite host and run hammer command.

Add ssh_username/password for [satellite] section

---

virtwho/register.py

Using hammer command to set satellite, handle organization and activation key, attach/remove subscription for host, and check the host-to-guest associations.
```
satellite = SatelliteCLI()
ret = satellite.org_id()
ret = satellite.org_add(name='test', label='test', description='test')
ret = satellite.org_delete(label='test')
ret = satellite.host_id(host_name=, host_uuid=, host_hwuuid=)
ret = satellite.subscription_id(pool='')
ret = satellite.attach(host_name=, host_uuid=, host_hwuuid=, pool=, quantity=)
ret = satellite.unattach(pool=, host_name=, quantity=)
ret = satellite.activation_key_create(key='test')
ret = satellite.activation_key_update(key='test', auto_attach='no')
ret = satellite.activation_key_attach(key='test', pool=)
ret = satellite.activation_key_unattach(key='test', pool=) …
```

Define satelliteCLI Class

---

virtwho/provision/virtwho_host.py

Define ```virtwho_host.py``` to install virt-who host, then init it and install virt-who package.
We can install virt-who package by ```repository```, ```gating msg``` or ```brew url```
Below is an example to use it.
```
python3 virtwho/provision/virtwho_host.py --rhel-compose=RHEL-9.0.0-20211227.3 --arch=x86_64 --host=hp-z220-99.qe.lab.eng.nay.redhat.com --brew-url=http://xxx/virt-who-1.31.17-1.el9.noarch.rpm
```

Define virtwho_host.py

---

virtwho/provision/virtwho_satellite.py

`virtwho_satellite.py`_ is used to deploy and configure satellite for virt-who testing.
It helps to install and initiate a host by beaker, install satellite pkg, deploy satellite server,
load manifest and set for virt-who testing.
* If need to install system by beaker, we should firstly set the [beaker] section in virtwho.ini.
* [beaker]
* client=
* client_username=
* client_password=
* default_username=
* default_password=
* keytab=
* principal=
* Define the register and repo information before deploying.
* cnd,  define the [rhsm] section in virtwho.ini
* dogfood, define the [satellite]:dogfood= in virtwho.ini
* We can optionally configure the [satellite] in virtwho.ini to replace some arguments.
* [satellite]
* server=
* username=
* password=
* ssh_username=
* ssh_passowrd=
* Below are …

Define the provision/virtwho_satellite.py

---

utils/satellite.py

`satellite.py`_ is used to deploy satellite by cdn or dogfood resource as a public tool.
1. Define the register and repo information before deploying.
* cnd,  define the [rhsm] section in virtwho.ini
* dogfood, define the [satellite]:dogfood= in virtwho.ini
2. Run the satellite.py with the required arguments.
* If we want to configure all arguments by command line, please run as below.
```# python3 satellite.py --version VERSION --repo REPO --rhel-compose COMPOSE_ID --server SERVER --ssh-username SSH_USERNAME --ssh-password SSH_PASSWORD --admin-username ADMIN_USERNAME --admin-password ADMIN_PASSWORD --manifest MANIFEST```
* We can also configure arguments by define the [satellite] section in virtwho.ini.
* [satellite]
* server=
* username=
* password=
* ssh_username=
* ssh_passowrd=
* …

Define the utils/satellite.py

---

utils/beaker.py

Define utils/beaker.py as public tool to install rhel os by beaker.
```
* Before run the file we need to set the [beaker] section in virtwho.ini.
* [beaker]
* client=
* client_username=
* client_password=
* default_username=
* default_password=
* keytab=
* principal=
* Below is an example to run the file with arguments.
```

Define utils/beaker.py as public tool

---

tests/conftest.py
virtwho.ini.sample

Update the `mode=` to `hypervisor=` in virtwho.ini, which is more clear

Update option name in virtwho.ini

---

virtwho/provision/virtwho_satellite.py

Update hostrequire of virtwho_satellite because ent2 server has been broken

Update hostrequire of virtwho_satellite because ent2 server has been broken

---

virtwho/provision/virtwho_host.py

Remove to define the default beaker-host to hp-z220, will define it in pipeline job. If no local mode involve in testing, will install a host from anywhere in beaker.

Remove to define the default beaker-host to hp-z220

---

tests/conftest.py
tests/gating/test_gating.py
virtwho/provision/virtwho_host.py
virtwho/runner.py

Define the test_gating.py, including
- test_debug
- test_interval
- test_oneshot
- test_hypervisor_id
Will add test_vdc_sku and test_host_guest_associates later
**Test Results**
#pytest tests/gating/test_gating.py
======================== test session starts ========================
platform linux -- Python 3.9.9, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
collected 4 items                                                                                                                                
tests/gating/test_gating.py ....                                                                                                           [100%]
========================== 4 passed in 441.27s (0:07:21) ===========

Define the test_gating.py

---

virtwho/provision/virtwho_satellite.py

The The dell-per740-69-vm-01/02/03/04 are ready in beaker, so add an option of `beaker-host` for user to select where to deploy satellite
- %dell-per740-69-vm%
- %hp-dl360g9-08-vm%'

Change the default beaker host to %dell-per740-69-vm% for satellite deployment

---

utils/properties_update.py
virtwho/provision/virtwho_host.py
virtwho/provision/virtwho_satellite.py

In the Jenkins jobs, the virtwho_host.py and virtwho_satellite.py are run meanwhile to parallel deploy virt-who host and satellite, but there is conflict when update the virtwho.ini, only the last update take effect because it covers the previous one.
So change to use the `utils/properties_update.py` to read and save the current file for each update action.

Fix issue of the virtwho.ini update conflict in virtwho_host.py and virtwho_satellite.py

---

virtwho/provision/virtwho_satellite.py
virtwho/register.py

The satellite `server` is deployed and write to the virthwo.ini file during the job process, so there is conflict to directly call the `config.satellite.server` from the virtwho.ini, which file is read at the beginning by `from virtwho.settings import config`, the server will be null and make trigger failed.
So add a new param `server=` for the Satellite() class to fix this issue.

add server=None param to class Satellite()

---

tests/function/test_config.py

Add test_debug_in_virtwho_conf case in test_config.py
```
(env) [hkx303@kuhuang function]$ pytest test_config.py -k test_debug
collected 3 items / 2 deselected / 1 selected                                                
test_config.py .                                                                       [100%]
========================= 1 passed, 2 deselected in 85.34s (0:01:25) =========================
```

Add test_debug_in_virtwho_conf case in test_config.py

---

virtwho/configure.py

Noted there is an issue:
1.
```
@pytest.mark.usefixtures('globalconf_clean')
def test_interval_in_virtwho_conf(self, virtwho, globalconf):
globalconf.update('global', 'debug', 'True')
globalconf.update('global', 'interval', '120')
```
-> result:
```
[root@rhel-8-6-0-20220420-3-esx-55913 ~]# cat /etc/virt-who.conf
[global]
interval=120
debug=True
```
2.
```
@pytest.mark.usefixtures('globalconf_clean')
def test_interval_in_virtwho_conf(self, virtwho, globalconf):
globalconf.update('global', 'interval', '120')
```
-> result is still:
```
[root@rhel-8-6-0-20220420-3-esx-55913 ~]# cat /etc/virt-who.conf
[global]
interval=120
debug=True
```
Found that after we cleaned the global conf,  the `self.cfg` wasn't be reset, and the `self.config.read(self.local_file)` wasn't be reset to …

Need to reset the self.cfg after cleaning VirtwhoGlobalConfig

---

pytest.ini
tests/conftest.py
tests/function/test_cli.py
virtwho/__init__.py
virtwho/runner.py

BTW: 
- Will define cases about option `-h` and `--version` in the `test_info.py`, which should only be run once at beginning.
- Will test the `-s` `-j` in each hypervisor test file, which should be tested for each file, not only for esx.
```
==================== test session starts ======================
collected 5 items                                                                                                                                
tests/function/test_cli.py::TestCli::test_debug PASSED               [ 20%]
tests/function/test_cli.py::TestCli::test_oneshot PASSED …
```

Define test cases of test_cli.py

---

tests/function/test_config.py

Add the case test_reporter_id_in_virtwho_conf in test_config file
```
pytest test_config.py -k test_reporter_id_in_virtwho_conf
collected 5 items / 4 deselected / 1 selected   
========================= 1 passed, 4 deselected in 91.66s (0:01:31) =========================
```

Add the test_reporter_id_in_virtwho_conf in test_config file

---

tests/function/test_service.py

```
===================== test session starts ======================
collected 4 items                                                                                                                                
tests/function/test_service.py::TestVirtwhoService::test_start_and_stop PASSED             [ 25%]
tests/function/test_service.py::TestVirtwhoService::test_restart PASSED                          [ 50%]
tests/function/test_service.py::TestVirtwhoService::test_try_restart PASSED                     [ 75%]
tests/function/test_service.py::TestVirtwhoService::test_force_reload …
```

Define test_service.py

---

tests/conftest.py
tests/function/test_cli.py

- Removed the `name='register_handler'` fixture, which could be replaced by `name='register_data'`, which should be more smart because there are different options for the `satellite` and `rhsm`, we don't need to separate them in cases any more.
- Removed the `name='hypervisor_handler'` fixture, which could be replaced by `name='hypervisor_data'`, there are different options for different hypervisors, we don't need to separate them in cases any more.
- New add `name='ssh_guest'`
- Updated the previous case in `test_cli`, replaced the `hypervisor_handler` by `hypervisor_data`.

Define new functions in conftest

---

virtwho/register.py

1. add to check the `and 'is already installed' not in output` in satellite_cert_install(), otherwise the cert cannot be installed when another one has been there.
2. change to return `False` in associate() function to be asserted in case.

Fix two function issues in virtwho/register.py

---

tests/function/test_config.py

Add log_per_config log_dir and log_file 3 cases in test_config.py
```
(env) [hkx303@kuhuang function]$  pytest test_config.py -k test_log_ 
collected 7 items / 5 deselected / 2 selected                                                
test_config.py ..                                                                      [100%]
======================== 2 passed, 5 deselected in 172.92s (0:02:52) =========================
```

Add log options related 2 cases in test_config.py

---

tests/conftest.py
tests/smoke/test_smoke.py
virtwho/register.py

```
================== test session starts ===================================
collected 6 items                                                                                                                                
tests/smoke/test_smoke.py::TestSmoke::test_host_guest_association PASSED                                                                   [ 16%]
tests/smoke/test_smoke.py::TestSmoke::test_rhsm_options PASSED                                                                             [ 33%]
tests/smoke/test_smoke.py::TestSmoke::test_rhsm_proxy PASSED …
```

define test_smoke.py with test_hypervisor_id, test_vdc_sku and test_temporary_sku

---

virtwho/configure.py

The previous code `self.hypervisor.server = f'''https://{hostname_get(ssh_rhevm)}:443/ovirt-engine'''` will change the original `self.hypervisor.server` value, which will impact the further using of the create() function.

update HypervisorConfig create() function to fix rhevm configure file issue

---

tests/smoke/test_smoke.py

test only on entry is left in satellite webui after run with hypervisor_id=uuid,hwuuid,hostname one by one
```
====================== test session starts ======================                                                                                                
tests/smoke/test_smoke.py::TestSmoke::test_hypervisor_id PASSED       [100%]
===================== 1 passed, 5 deselected in 186.78s (0:03:06) ===========
```

update test_smoke with the test_hypervisor_id case

---

tests/conftest.py
tests/sca/test_sca.py
virtwho/register.py

```
================== test session starts ========================
collected 4 items                                                                                                                                
tests/sca/test_sca.py::TestSCA::test_hypervisor_facts PASSED                            [ 25%]
tests/sca/test_sca.py::TestSCA::test_host_to_guest_association PASSED            [ 50%]
tests/sca/test_sca.py::TestSCA::test_guest_entitlement_status PASSED              [ 75%]
tests/sca/test_sca.py::TestSCA::test_hypervisor_entitlement_status PASSED                         [100%] …
```

Define test_sca.py with test_hypervisor_facts/host_to_guest_association/guest_entitlement_status

---

virtwho/provision/virtwho_hypervisor.py

- This file will used to manage and check all the hypervisor status by command `#virtwho_hypervisor.py {hypervisor mode}`, it will help to get all the test necessary values in virtwho.ini file, including host server, uuid, hostname, version, cpu, guest_ip and guest_uuid.
- If the hypervisor server or guest down, will update the `status = BAD (Server Down)`/`status = BAD (Guest Broke)` and `server=Down`
- If the guest pause, will try to resume it
- If the guest shut off, will try to start it
- If failed to start the guest, will mark `guest_ip=None`
- If any value changed, will give log warning and updated the virtwho.ini file to `guest_ip=10.10.10.10 (Updated)`
```
[2022-08-11 11:07:37] - [virtwho_hypervisor.py] - INFO: +++ Start to test the Libvirt …
```

Define the virtwho_hypervisor.py for libvirt mode

---

virtwho/provision/virtwho_hypervisor.py

Provide to check the below options of vCenter environment
If fail: `esx_status = BAD (Server Broke)`
If fail:  `esx_status = BAD (Server Broke)`  `esx_ip=Broke` `guest_ip=None`
If fail:  `esx_status = BAD (Windows Client Broke)`  `guest_ip=None`
If fail:  redeploy a new one
If there are data changes, will directly updated the new value to virtwho.ini and mark with `UPDATED`

define virtwho_hypervisor.py with esx mode

---

virtwho/provision/virtwho_hypervisor.py
virtwho/runner.py

```
====================== test session starts ======================
collected 4 items / 3 deselected / 1 selected                                                                                                    
tests/sca/test_sca.py::TestSCA::test_hypervisor_facts PASSED             [100%]
================= 1 passed, 3 deselected, 1 warning in 65.78s (0:01:05) ==========
```

Fix the hypervisor.version type issue and remove 'raise Fail' from each step.

---

tests/conftest.py
tests/hypervisor/conftest.py
tests/hypervisor/test_esx.py
virtwho/__init__.py
virtwho/base.py
virtwho/configure.py

```
[hkx303@kuhuang virtwho-test]$ pytest tests/hypervisor/test_esx.py  -k test_encrypted_password -s
collected 6 items / 5 deselected / 1 selected                                                
======================== 1 passed, 5 deselected in 184.50s (0:03:04) =========================
```

add the test_encrypted_password case for the esx hypervisor

---

tests/hypervisor/test_hypervisors_state.py

The test file name is `test_hypervisors_state.py`, and there was one test case `test_hyperv()`, so when run `pytest test_hypervisors_state.py -k test_hyperv`, it will still run all the test cases under `test_hypervisors_state.py` because the test file name contains the test case name.
So updated the test case name to fix the issue.

update the test case name due to conflict with the test file name

---

tests/hypervisor/test_hypervisors_state.py
virtwho/provision/virtwho_hypervisor.py

- Remove the duplicated function `hypervisor_state`, we can directly call the `esx_monitor, hyperv_monitor`.
- Add `return hyperv_state, esx_state...` to support the assertion in test cases.
```
================== test session starts ====================
collected 7 items / 4 deselected / 3 selected                                                                                                    
tests/hypervisor/test_hypervisors_state.py::TestHypervisorsState::test_state_esx PASSED           [ 33%]
tests/hypervisor/test_hypervisors_state.py::TestHypervisorsState::test_state_hyperv PASSED …
```

perfect the virtwho_hypervisor.py and test_hypervisors_state.py

---

virtwho/base.py
virtwho/provision/virtwho_hypervisor.py

- Define the kubevirt for virtwho_hypervisors.py
- Fix if branch issues for esx, libvirt and hyperv
Test Results
```
======================== test session starts ========================
collected 7 items / 3 deselected / 4 selected                                                                                                   
tests/hypervisor/test_hypervisors_state.py::TestHypervisorsState::test_state_esx PASSED       [ 25%]
tests/hypervisor/test_hypervisors_state.py::TestHypervisorsState::test_state_hyperv PASSED       [ 50%]
tests/hypervisor/test_hypervisors_state.py::TestHypervisorsState::test_state_kubevirt …
```

Define the kubevirt for virtwho_hypervisors.py

---

virtwho/provision/virtwho_hypervisor.py

Define ahv mode for virtwho_hypervisor.py
```
============== test session starts ======================
collected 7 items / 6 deselected / 1 selected                                                                                                  
tests/hypervisor/test_hypervisors_state.py::TestHypervisorsState::test_state_ahv PASSED      [100%]
=================== 1 passed, 6 deselected, 1 warning in 11.53s ==================
```

define ahv mode for virtwho_hypervisor.py

---

virtwho/base.py
virtwho/provision/virtwho_hypervisor.py

- for kubevirt:  use `ssh_connect` instead of `host_ping` to test the guest, because the guest contains individual port.
- for esx: individually to get the esx_hostname because the hosename got from hypervisor-builder maybe a guest_ip, which depends on the definition in vCenter server.

perfect the virtwho_hypervisor.py: esx and kubevirt

---

tests/hypervisor/test_esx.py

Add test case around simplified_vim option for esx hypervisor
```
[hkx303@kuhuang virtwho-test]$ pytest tests/hypervisor/test_esx.py -k test_simplified_vim -s
collected 14 items / 13 deselected / 1 selected   
======================== 1 passed, 13 deselected in 93.44s (0:01:33) =========================
```

Add test case around simplified_vim option for esx hypervisor

---

tests/hypervisor/test_esx.py
virtwho/__init__.py
virtwho/configure.py
virtwho/runner.py

Add the test_fake_mode case for esx hypervisor in test_esx.py
```
[hkx303@kuhuang virtwho-test]$ pytest tests/hypervisor/test_esx.py -k test_fake_type
collected 13 items / 12 deselected / 1 selected  
======================== 1 passed, 12 deselected in 98.13s (0:01:38) =========================
```

Add the test_fake_mode case for esx hypervisor

---

tests/hypervisor/conftest.py
tests/hypervisor/test_rhevm.py

Create the test_rhesm.py cloning the test_esx.py, need to debug it one by one, will select the checkbox for every case once I debug it.
Positive:
Negative:
```
[hkx303@kuhuang virtwho-test]$ pytest -v tests/hypervisor/test_rhevm.py::TestRHEVMPositive::test_encrypted_password -s
platform linux -- Python 3.7.3, pytest-5.4.3, py-1.8.0, pluggy-0.13.1 -- /usr/bin/python3
collected 1 item  
PASSED
================================ 1 passed in 60.25s (0:01:00) …
```

Create the test_rhesm.py cloning the test_esx.py

---

tests/hypervisor/conftest.py
tests/hypervisor/test_hyperv.py

Positive
Negative
```
[hkx303@kuhuang virtwho-test]$ pytest -v tests/hypervisor/test_hyperv.py::TestHypervPositive::test_encrypted_password -s
platform linux -- Python 3.7.3, pytest-5.4.3, py-1.8.0, pluggy-0.13.1 -- /usr/bin/python3
collected 1 item
PASSED
===================================== 1 passed in 59.69s =====================================
[hkx303@kuhuang virtwho-test]$ pytest -v tests/hypervisor/test_hyperv.py::TestHypervPositive::test_hypervisor_id -s …
```

Add cases for hyperv hypervisor

---

tests/conftest.py
tests/hypervisor/conftest.py
tests/hypervisor/test_kubevirt.py

TestKubevirtPositive
TestKubevirtNegative
```
[hkx303@kuhuang virtwho-test]$ pytest tests/hypervisor/test_kubevirt.py -k test_hypervisor_id -s
================================ test session starts ================================
collected 11 items / 10 deselected / 1 selected
.
=================== 1 passed, 10 deselected in 132.67s (0:02:12) ====================
[hkx303@kuhuang virtwho-test]$ pytest tests/hypervisor/test_kubevirt.py::TestKubevirtPositive::test_filter_hosts -s
==================================== test session starts …
```

Add positive and negative cases for kubevirt mode

---

virtwho/provision/virtwho_host.py

No need to create repo individually because all the hosts will be deployed by beaker, so the correct repo will be here normally as default.

maintain virtwho_host.py to comment create repo

---

virtwho/base.py
virtwho/provision/virtwho_host.py

- update the `base.host_ping()` to use `-c` to support the both linux and mac os, mac doesn't support the `-w`
- update `virtwho_host.py` for gating test, will firstly try to ping and use the solid virt-who host, if fail to ping will deploy a new one by beaker.

virtwho_host: perfet to support the stable hosts for gating test

---

tests/hypervisor/conftest.py
tests/hypervisor/test_ahv.py

Positive
Negative
```
[hkx303@kuhuang virtwho-test]$ pytest tests/hypervisor/test_ahv.py::TestAHVPositive::test_encrypted_password
collected 1 item
tests/hypervisor/test_ahv.py .                                                         [100%]
================================ 1 passed in 73.60s (0:01:13) ================================
[hkx303@kuhuang virtwho-test]$ pytest tests/hypervisor/test_ahv.py::TestAHVPositive::test_hypervisor_id …
```

Add test cases for ahv hypervisor

---

virtwho/provision/virtwho_satellite.py

`%dell-per740-69-vm%` beaker hosts don't support to deploy the `RHEL-8.7.0-20221013.1`, so change to a common `RHEL-8.7.0`.

virtwho_satellite: update compose id for rhel8

---

utils/properties_update.py
virtwho/base.py
virtwho/provision/virtwho_hypervisor.py

- define the new function `rhel_host_uuid_get` to get correct uuid from guest side, not from vcenter side by powercli

virtwho_hypervisor: maintain for esx to get correct guest_uuid

---

tests/conftest.py
tests/function/test_cli.py
tests/function/test_config.py
tests/function/test_service.py
tests/gating/test_gating.py
tests/hypervisor/test_ahv.py
tests/hypervisor/test_esx.py
tests/hypervisor/test_hyperv.py
tests/hypervisor/test_kubevirt.py
tests/hypervisor/test_libvirt.py
tests/hypervisor/test_rhevm.py
tests/package/test_upgrade_downgrade.py
tests/sca/test_sca.py
tests/smoke/test_smoke.py

- define each function and class fixtures starting with `function_` or `class_`.
- add a new fixture `class_virtwho_d_conf_clean`, which should be called in `tests/function/test_config.py`, otherwise it will run all the hypervisors under /etc/virt-who.d/

update several fixtures in cases due to the name changes in conftest

---

tests/conftest.py
tests/subscription/test_rhsm.py
tests/subscription/test_satellite.py
virtwho/__init__.py
virtwho/configure.py
virtwho/register.py
virtwho/runner.py

**test_rhsm.py:**
**test_satellite.py**
```
**% pytest --disable-warnings -v tests/subscription/test_satellite.py**                                  
collected 7 items                                                                                                                     
tests/subscription/test_satellite.py::TestSatellite::test_vdc_virtual_pool_attach_by_poolId PASSED                              [ 14%] …
```

design testcase for test_rhsm and test_satellite

---

virtwho/provision/virtwho_hypervisor.py

We have deployed stable rhel guests in ahv and kubevirt hypervisors to support the con-work with subscription watch team, so now we should maintain our hypervisor-monitor to support testing the new guests.
```
% pytest --disable-warnings -v tests/hypervisor/test_hypervisors_state.py -k 'ahv or kubevirt'
collected 7 items / 5 deselected / 2 selected …
```

hypervisor-monitor: to support more guests for ahv and kubevirt modes

---

tests/hypervisor/test_hypervisors_state.py
tests/hypervisor/test_hypervisors_sw.py
virtwho/configure.py
virtwho/register.py
virtwho/runner.py

**Test Steps**
When the hypervisor/guest change, we will run the test case to report the latest mapping to the specified stage account.
1. delete all hosts from the account
2. register virt-who host to the stage
3. run virt-who to report mappings 
4. register guests
```
% pytest --disable-warnings -v tests/hypervisor/test_hypervisors_sw.py
collected 1 item …
```

Design test case to report hypervisor for subscription watch team

---

tests/function/test_cli.py
tests/function/test_service.py
virtwho/base.py
virtwho/configure.py
virtwho/runner.py

```
% pytest --disable-warnings -v tests/function/test_service.py                   
collected 8 items                                                                                                                     
tests/function/test_service.py::TestVirtwhoService::test_virtwho_service_start_and_stop PASSED                                  [ 12%]
tests/function/test_service.py::TestVirtwhoService::test_virtwho_service_ …
```

add virt-who cli and service related cases

---

utils/satellite.py
virtwho/provision/virtwho_satellite.py
virtwho/register.py

- As the following release note of satellite6.13, use option `--tuning development` to replace the `--disable-system-checks` when >= `6.13`
```
The --disable-system-checks option has been removed from the satellite-installer. A Satellite installation now requires the minimum recommended system resources to be allocated. For non-production deployments, and only if absolutely necessary, you can use --tuning development as an alternative option. 
```
- move function `satellite_manifest_upload` to `virtwho_satellite.py` from `utils/satellite.py` to make it specified only for virt-who testing.
- fix the org create issue when it already exists.
- fix the manifest upload issue by removing it before uploading.

Perfect the satellite deployment process

---

tests/function/test_service.py
tests/package/test_install_uninstall.py
tests/package/test_upgrade_downgrade.py
utils/beaker.py
utils/docker.py
utils/kickstart.py
utils/parse_ci_message.py
utils/polarion_testcase_upload.py
utils/properties_update.py
utils/satellite.py
virtwho/base.py
virtwho/provision/virtwho_host.py
virtwho/provision/virtwho_hypervisor.py
virtwho/provision/virtwho_satellite.py
virtwho/register.py

- Define a new function in base named `virtwho_package_url`
- Update case package/test_install_uninstall.py/test_install_uninstall_by_rpm to use the the new function
- Update case package/test_upgrade_downgrade.py/test_install_uninstall_by_rpm to use the the new function 
```
% pytest --disable-warnings -v tests/package/ -k 'by_rpm'
collected 11 items / 9 deselected / 2 selected …
```

fix the package_url issue

---

virtwho/runner.py

Kunxin have mentioned the msg inaccurate revise in Linter set up PR, which can see the comments here:
https://github.com/VirtwhoQE/virtwho-test/pull/141
I have been fixed this two msg error in this PR.

Fix msg bugs in send_number function caused by linter intergration PR

---

tests/hypervisor/test_rhevm.py
virtwho/configure.py

Add test case test_url_without_ovirt_engine from [tc_2055_validate_rhevm_url_without_ovirt_engine.py](https://github.com/VirtwhoQE/virtwho-ci/blob/master/tests/tier2/tc_2055_validate_rhevm_url_without_ovirt_engine.py)
Need the value `rhevm_hypervisor_url `from `VirtwhoHypervisorConfig`
```
[hkx303@kuhuang virtwho-test]$ pytest tests/hypervisor/test_rhevm.py -k test_url_without_ovirt_engine -s
collected 13 items / 12 deselected / 1 …
```

Add test case test_url_without_ovirt_engine

---

tests/conftest.py
tests/hypervisor/test_default.py

Add test case: test_virtwho_status from https://github.com/VirtwhoQE/virtwho-ci/blob/master/tests/tier1/tc_1113_check_virtwho_status.py
```
[hkx303@kuhuang virtwho-test]$ pytest tests/hypervisor/test_default.py -k test_virtwho_status -s
collected 6 items / 5 deselected / 1 selected    
========================= 1 passed, 5 deselected in 68.73s (0:01:08) =========================
```

Add test case: test_virtwho_status

---

tests/conftest.py
tests/hypervisor/test_kubevirt.py

Add test case: test_insecure for kubevirt test file
```
[hkx303@kuhuang virtwho-test]$ pytest tests/hypervisor/test_kubevirt.py -k test_insecure -s
collected 8 items / 7 deselected / 1 selected  
======================== 1 passed, 7 deselected in 246.10s (0:04:06) =========================
```

Add test case: test_insecure for kubevirt test file

---

utils/__init__.py
utils/beaker.py
utils/docker.py
utils/ini2json.py
utils/kickstart.py
utils/parse_ci_message.py
utils/parse_test_result.py
utils/polarion_testcase_upload.py
utils/properties_update.py
utils/satellite.py
virtwho/base.py
virtwho/provision/virtwho_host.py
virtwho/provision/virtwho_hypervisor.py
virtwho/provision/virtwho_satellite.py

Changed for the `ahv` and `kubevirt`, will skip to test the guest_sw when the value is null.
```
% pytest --disable-warnings -v tests/hypervisor/test_hypervisors_state.py -k 'ahv or kubevirt'
collected 7 items / 5 deselected / 2 selected                                                                                         
tests/hypervisor/test_hypervisors_state.py::TestHypervisorsState::test_state_kubevirt PASSED …
```

Maintain the virtwho_hypervisor.py for ahv and kubevirt around guest_sw

---

pytest.ini
tests/package/test_info.py
virtwho/provision/virtwho_host.py

Two cases `test_install_uninstall_by_rpm` and `test_upgrade_downgrade_by_rpm` failed in jenkins job https://main-jenkins-csb-virtwhoqe.apps.ocp-c1.prod.psi.redhat.com/job/regression-el9/job/package-runtest/5/console, which was because no the `wget` package found for downloading. So updated the `virtwho-host.py` to default install the package.
```
% pytest --disable-warnings -v tests/package/ -k 'test_install_uninstall_by_rpm or test_upgrade_downgrade_by_rpm'
rootdir: /Users/yuefliu/workspace/virtwho-test, configfile: …
```

package cases debug: default to install the wget when deploy virt-who host

---

tests/conftest.py
tests/subscription/test_rhsm.py
tests/subscription/test_satellite.py
virtwho/provision/virtwho_rhsm.py
virtwho/provision/virtwho_satellite.py
virtwho/register.py

```
% pytest --disable-warnings -v tests/subscription/test_satellite.py -k 'test_vdc_virtual_pool_attach_by_poolId'
collected 9 items / 8 deselected / 1 selected                                                                                         
tests/subscription/test_satellite.py::TestSatelliteScaDisable::test_vdc_virtual_pool_attach_by_poolId PASSED                    [100%]
======================================== 1 passed, 8 …
```

support the sca mode changing

---

utils/satellite.py

Should disable the rhsm sca mode to attach sku and enable required repos for the Satellite deployment.

utils/satellite.py: disable rhsm sca mode to support satellite deployment

---

utils/polarion_testcase_upload.py
utils/polarion_testrun_import.py

We can locally import a testrun result.xml file by run below command
```
python3 utils/polarion_testrun_import.py --url=${url} --username=${username} --password=${password} 
--project=${project} --id=${id} --title=${title} --assignee=${assignee} --composeid=${rhel_compose} --component=${component}  --build=${build} --jenkinsjobs=${JENKINS_BUILD_ID} --plannedin=${POLARION_PLANS} --subsystemteam=${sst} --type=regression --xml-file=results.xml --directory=${directory} --source-code=tests
```
Note: the type and subsystemteam didn't take work after debugging, will continue debug it when there are new requirement.

New define utils/polarion_testrun_import.py

---

utils/polarion_testrun_import.py

as subject to match the pipeline job because the results.xml may not in the directory of `virtwho-test`

utils/polarion_testrun_import.py: debug the file directory issue

---

utils/polarion_testrun_import.py

utils/polarion_testrun_import.py: replace unsupported characters

---

tests/function/test_config.py

The case failed due to the error info:
`AssertionError: assert '09a33b42-d988-8179-3ae7-ac341efae918' in ''`
the root cause is the `virt-who` command cannot be run successfully when the virt-who thread starts
```
(env) [hkx303@kuhuang virtwho-test]$ pytest tests/function/test_config.py -k test_print_in_virtwho_conf -s
plugins: …
```

Fix the test case: test_print_in_virtwho_conf

---

tests/function/test_config.py

Fix test case: test_interval_in_virtwho_conf, the result["loop"] is not always 60s, might also 61s
```
(env) [hkx303@kuhuang virtwho-test]$ pytest tests/function/test_config.py -k test_interval_in_virtwho_conf -s
collected 21 items / 20 deselected / 1 selected …
```

Fix test case: test_interval_in_virtwho_conf

---

virtwho/register.py

case test_hypervisor_id_in_virtwho_conf failed for the Nutanix hypervisor due to the error info:
```
>                   assert satellite.host_id(hypervisor_data["hypervisor_hostname"])
E                   AssertionError: assert None
E                    +  where None = <bound method Satellite.host_id of <virtwho.register.Satellite object at 0x7f05f9c83b80>>('NTNX-089019a9-A')
E                    +    where <bound method Satellite.host_id of <virtwho.register.Satellite object at 0x7f05f9c83b80>> = <virtwho.register.Satellite object at 0x7f05f9c83b80>.host_id
```
the root cause is the hostname of Nutanix is capital,  cannot match the name from the hammer command output, need to transfer it
```
(env) [hkx303@kuhuang virtwho-test]$ pytest …
```

Fix test case: test_hypervisor_id_in_virtwho_conf

---

tests/function/test_cli.py
tests/function/test_config.py

As per [BZ1448821](https://bugzilla.redhat.com/show_bug.cgi?id=1448821), we don't have related notice log for kubevirt, hyperv and rhevm hypervisors, need to skip the assertion for these hypervisors
Need to add the steps to the following 3 cases:
All test cases passed locally

Fix test one shot cases for kubevirt, hyperv and rhevm hypervisors

---

tests/subscription/test_rhsm_option.py

Cases failed as cannot get the expected error info from `result["error_msg"]`:
```
[2023-05-31 17:35:44] - [ssh.py] - INFO: >>> grep '\[.*ERROR.*\]' /var/log/rhsm/rhsm.log |sort
[2023-05-31 17:35:44] - [ssh.py] - INFO: <<< stdout
2023-05-31 05:35:15,294 [virtwho.destination_-3953841796083599115 ERROR] MainProcess(955685):Thread-3 @virt.py:run:421 - Thread 'destination_-3953841796083599115' fails with exception:
```
Need to change to `result["log"]` for the following cases:
Test Result
All test cases passed locally

Update test cases for test_rhsm_option file

---

tests/subscription/test_satellite.py

cases test_non_default_org_with_rhsm_options and test_non_default_org_without_rhsm_options failed due to the error msg:
`TypeError: 'NoneType' object is not subscriptable`
The root cause it the second org is still sca enabled, so failed to attach the subscription
Test cases passed locally

Fix test cases: test_non_default_org_with and without_rhsm_options

---

utils/polarion_testrun_import.py

**Local test result**
```
[2023-06-06 16:58:14] - [polarion_testrun_import.py] - INFO: {
"files" : {
"polarion_testrun.xml" : {
"job-ids" : [ 3440071 ]
}
}
}
[2023-06-06 16:58:14] - [polarion_testrun_import.py] - INFO: Successed to import xml to polarion
```

polarion_testrun_import: change to use the default testrun id

---

virtwho/provision/virtwho_host.py

15s is not enough for the guest starting in local mode, so change to 30s.

Extented to wait for 30s after adding vm for local mode

---

tests/hypervisor/test_local.py

Add test case: test_threads_number_after_reconfig_libvirt from [tc_1103_check_virtwho_threads_number_after_reconfig_libvirt.](https://github.com/VirtwhoQE/virtwho-ci/blob/master/tests/tier1/tc_1103_check_virtwho_threads_number_after_reconfig_libvirt.py)
```
[hkx303@kuhuang virtwho-test]$ pytest tests/hypervisor/test_local.py -k test_threads_number_after_reconfig_libvirt -s
=================================== test session starts ===================================
collected 1 item    
============================== 1 passed in …
```

Add test case: test_threads_number_after_reconfig_libvirt

---

tests/function/test_cli.py
tests/function/test_config.py
tests/function/test_service.py
tests/hypervisor/test_default.py
tests/hypervisor/test_local.py
tests/package/test_upgrade_downgrade.py

local mode doesn't support the rhsm_x options, so need to register virt-who host.

register virt-who host when run for local mode

---

tests/hypervisor/test_rhevm.py

Test case failed due to the error msg:
`AttributeError: 'RHSM' object has no attribute 'delete'`, need to update the case
Passed locally

Fix test case: test_hypervisor_id

---

tests/hypervisor/conftest.py
tests/hypervisor/test_ahv.py

Ahv cases for rhel8 failed due to the error msg:
` -1 and 'internal error: Unable to parse URI qemu+ssh' in "2023-06-08 22:05:41,318 [virtwho.main ERROR] MainProcess(311267):Thread-2 @virt.py:run:416 - Thread 'virtwho-ahv' fails with error: HTTP Auth Failed get https://10.73.131.191:9440/api/nutanix/v2.0/clusters. \n")`
The assersion info for rhel8 is not correct, need to update
All passed locally

Fix the ahv_assersion function for ahv test cases

---

tests/function/test_config.py
tests/subscription/test_satellite.py
virtwho/configure.py

Debug Function&Subscription failed test cases in rhel9.3.0 CTC1

---

tests/function/test_config.py
tests/hypervisor/test_default.py
tests/subscription/test_satellite.py
virtwho/configure.py
virtwho/register.py

All the cases were rerun pass locally.

Debug Libvirt local failed test cases in rhel9.3.0 CTC1

---

tests/conftest.py
tests/hypervisor/conftest.py
tests/hypervisor/test_default.py
tests/hypervisor/test_esx.py
tests/hypervisor/test_kubevirt.py

Debug Hypervisor failed test cases in rhel9.3.0 CTC1

---

virtwho/provision/virtwho_host.py

As subject, to fix the error when starting the guest:
```
Traceback (most recent call last):
File "/home/jenkins/workspace/regression-el8/REGRESSION-TRIGGER/virtwho-test/virtwho/provision/virtwho_host.py", line 353, in <module>
provision_virtwho_host(args)
File "/home/jenkins/workspace/regression-el8/REGRESSION-TRIGGER/virtwho-test/virtwho/provision/virtwho_host.py", line 111, in provision_virtwho_host
virtwho_ini_props_update(args)
File "/home/jenkins/workspace/regression-el8/REGRESSION-TRIGGER/virtwho-test/utils/properties_update.py", line 18, in virtwho_ini_props_update
config.update(args.section, args.option, args.value)
File "/home/jenkins/workspace/regression-el8/REGRESSION-TRIGGER/virtwho-test/virtwho/settings.py", line 56, in update
self.config.set(section, option, value)
File …
```

Expand the time sleep when starting the libvirt guest

---

tests/hypervisor/test_default.py

**Descirption**
Update the step about `check host-to-guest association in rhsm.log`
```
(env) [hkx303@kuhuang virtwho-test]$ pytest tests/hypervisor/test_default.py -k test_associated_info_by_rhsmlog_and_webui -s
collected 6 items / 5 deselected / 1 selected   
=============== 1 passed, 5 deselected, …
```

Update test case test_associated_info_by_rhsmlog_and_webui

---

virtwho/provision/virtwho_host.py

Sometime the guest hostname of local libvirt is abnormal, such as `unused, localhost...`, so perfect the code to redefine a random hostname for this condition.

virtwho_host.py: define hostname for local mode

---

tests/subscription/test_rhsm.py
tests/subscription/test_satellite.py

test_rhsm.py
test_satellite.py
**rhsm+esx**
```
% pytest --disable-warnings -v tests/subscription/test_rhsm.py -k 'test_hypervisor_entitlement_status or test_guest_entitlement_status'
collected 8 items / 6 deselected / 2 selected                                                                                         
tests/subscription/test_rhsm.py::TestRhsmScaEnable::test_hypervisor_entitlement_status PASSED                                   [ 50%] …
```

design the sca/enable cases around subscription

---

tests/package/test_upgrade_downgrade.py

test case test_upgrade_downgrade_by_yum failed when downgrade the virt-who package with the error msg:
```
Errors during downloading metadata for repository 'rhel-8-for-x86_64-baseos-beta-rpms':
- Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://cdn.redhat.com/content/beta/rhel8/8/x86_64/baseos/os/repodata/repomd.xml [SSL certificate problem: self signed certificate in certificate chain]
Error: Failed to download metadata for repo 'rhel-8-for-x86_64-baseos-beta-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```
we added the step: `function_host_register_for_local_mode`, but need to disable the sca mode to install the package
```
(env) [hkx303@kuhuang …
```

Fix test case: test_upgrade_downgrade_by_yum for libvirt-local mode

---

tests/hypervisor/test_default.py

test case `test_associated_info_by_rhsmlog_and_webui` failed for local mode due to the error msg:
`KeyError: 'Default_Organization'`， the mapping info for local mode is different from other hypervisors, need to update the test case
```
(env) [hkx303@kuhuang virtwho-test]$ pytest tests/hypervisor/test_default.py -k test_associated_info_by_rhsmlog_and_webui -s
rootdir: /home/hkx303/Documents/CI/virtwho-test, inifile: …
```

Fix test case test_associated_info_by_rhsmlog_and_webui for local mode

---

utils/satellite.py
virtwho/provision/virtwho_satellite.py

Support satelite6.14 for smoke testing, now deploy the satellite y stream need the value `snap version`, need to update the satellite deploy function
```
[2023-06-27 20:44:54] - [register.py] - INFO: Succeeded to create activation key:Virtwho_AK
[2023-06-27 20:44:54] - [virtwho_satellite.py] - INFO: +++ Succeeded to deploy the Satellite 6.14-repo-rhel8/dell-per740-69-vm-01.lab.eng.pek2.redhat.com +++
```

Support satelite6.14 for smoke testing

---

tests/others/test_hypervisors_sw.py
tests/smoke/test_smoke.py

update docstring for the test_hypervisor_sw case and test_smoke case

---

virtwho/provision/virtwho_hypervisor.py

From the result of the hypervisor_monitor, the kubevirt config file didn't update, but the result is still GOOD, need to analyze and fix it

Fix the compare step for kubevirt in hypervisor-monitor

---

tests/hypervisor/test_multi_hypervisors.py
virtwho/base.py

**Descirption**
Add test case to test_multi_hypervisors.py
Test Result
```
(env) [hkx303@kuhuang virtwho-test]$ pytest tests/hypervisor/test_multi_hypervisors.py -s
collected 1 item   
=========================== 1 passed in 298.74s (0:04:58) ============================
```

Add test case to test_multi_hypervisors.py

---

tests/hypervisor/test_esx.py
virtwho/runner.py

The test case `test_extension_file_name` [failed](https://main-jenkins-csb-virtwhoqe.apps.ocp-c1.prod.psi.redhat.com/job/regression-el8/job/hypervisor-runtest/17/testReport/junit/tests.hypervisor.test_esx/TestEsxNegative/test_extension_file_name/) due to:
```
>       assert (
result["error"] is not 0
and result["send"] == 0
and result["thread"] == 1
and error_msg in result["error_msg"]
and warning_msg in result["warning_msg"]
)
E       assert (0 is not 0)
tests/hypervisor/test_esx.py:1032: AssertionError
```
It is because we are now also have the libvirt mode on host, need to update the test case.
```
[hkx303@kuhuang virtwho-test]$ pytest tests/hypervisor/test_esx.py -k test_extension_file_name -s
==================== 1 passed, 28 deselected, 1 warning in …
```

Fix the case test_extension_file_name

---

tests/hypervisor/test_kubevirt.py

Test case test_type [failed](https://main-jenkins-csb-virtwhoqe.apps.ocp-c1.prod.psi.redhat.com/job/regression-el8/job/hypervisor-runtest/33/testReport/junit/tests.hypervisor.test_kubevirt/TestKubevirtNegative/test_type/) failed due to the error msg:
```
>       assert (
result["error"] is not 0
and result["send"] == 0
and result["thread"] == 1
and assertion["disable"] in result["error_msg"]
)
E       assert (0 is not 0)
```
It is because we also have the local hypervisor on the virt-who host, need to update test case
```
[hkx303@kuhuang virtwho-test]$ pytest tests/hypervisor/test_kubevirt.py -k test_type -s
platform linux -- Python 3.7.3, pytest-5.4.3, py-1.8.0, …
```

Fix the test case test_type for kubevirt

---

tests/hypervisor/test_libvirt.py

case `test_server` [failed](https://main-jenkins-csb-virtwhoqe.apps.ocp-c1.prod.psi.redhat.com/job/regression-el8/job/hypervisor-runtest/21/testReport/junit/tests.hypervisor.test_libvirt/TestLibvirtNegative/test_server/) due to the error msg:
```
>       assert (
result["error"] is not 0
and result["send"] == 0
and result["thread"] == 1
and assertion["disable"] in result["error_msg"]
)
E       assert (0 is not 0)
```
it is because         
```
```
need to update test case
```
[hkx303@kuhuang virtwho-test]$ pytest tests/hypervisor/test_libvirt.py -k test_server -s
rootdir: …
```

Fix test case test_server for libvirt-remote mode

---

virtwho/runner.py

Test case `test_extension_file_name` for satellite [failed](https://main-jenkins-csb-virtwhoqe.apps.ocp-c1.prod.psi.redhat.com/job/regression-el8/job/hypervisor-runtest/25/testReport/junit/tests.hypervisor.test_esx/TestEsxNegative/test_extension_file_name/) due the error msg:
```
>       assert (
result["error"] is not 0
and result["send"] == 0
and result["thread"] == 1
and error_msg in result["error_msg"]
and warning_msg in result["warning_msg"]
)
E       assert (0 is not 0)
```
Need to update the send_number function for satellite to fix this issue
```
[hkx303@kuhuang virtwho-test]$ pytest tests/hypervisor/test_esx.py -k test_extension_file_name -s
platform linux -- …
```

Update the send_number function for satellite

---

tests/subscription/test_rhsm.py
tests/subscription/test_satellite.py

The test case test_guest_entitlement_status failed due to the error msg:
https://main-jenkins-csb-virtwhoqe.apps.ocp-c1.prod.psi.redhat.com/job/regression-el8/job/subscription-runtest/15/testReport/junit/tests.subscription.test_rhsm/TestRhsmScaEnable/test_guest_entitlement_status/
```
AssertionError: assert False
+  where False = msg_search('+-------------------------------------------+\n   System Status Details\n+-------------------------------------------...nRed Hat Enterprise Linux for x86_64:\n- Not supported by a valid subscription.\n\nSystem Purpose Status: Disabled\n\n', 'Content Access Mode is set to Simple Content Access. This host has access to content, regardless of subscription status.')
```
```
[hkx303@kuhuang virtwho-test]$ pytest …
```

Fix test case test_guest_entitlement_status

---

tests/function/test_config.py

test case test_interval_in_virtwho_sysconfig failed due to the error msg:
```
>       assert result["send"] == 1 and result["error"] == 0 and result["loop"] == 60
E       assert (1 == 1
E         +1
E         -1 and 0 == 0
E         +0
E         -0 and 61 == 60
E         +61
E         -60)
```
Need to add the time option for loop time assertion
test for kubevirt hypervisor
```
[hkx303@kuhuang virtwho-test]$ pytest tests/function/test_config.py -k test_interval_in_virtwho_sysconfig -s
==================== 1 passed, 20 deselected in 150.17s (0:02:30) ====================
```

Fix test case test_interval_in_virtwho_sysconfig

---

tests/hypervisor/test_local.py

Test case tests.hypervisor.test_local.TestLocalPositive.test_threads_number_after_reconfig_libvirt failed for rhel9 as cannot start the libvird service as the following msg:
```
[root@hp-z220-05 ~]# service libvirtd status 
Redirecting to /bin/systemctl status libvirtd.service 
○ libvirtd.service - Virtualization daemon 
Loaded: loaded (/usr/lib/systemd/system/libvirtd.service; enabled; preset: disabled) 
Active: inactive (dead) since Fri 2023-07-28 10:10:03 EDT; 2min 56s ago 
Duration: 525ms 
TriggeredBy: ● libvirtd-admin.socket 
● libvirtd-ro.socket 
● libvirtd.socket 
○ libvirtd-tls.socket 
○ libvirtd-tcp.socket 
Docs: man:libvirtd(8) 
https://libvirt.org 
Process: 3753 ExecStart=/usr/sbin/libvirtd $LIBVIRTD_ARGS (code=exited, status=0/SUCCESS) 
Main PID: 3753 …
```

Fix case test_threads_number_after_reconfig_libvirt for libvirt-lcoal on rhel9

---

tests/conftest.py

We need to add test log for test cases to identify what is the test case name for the log, so that we could see the failed cases directly
```
[2023-08-09 15:12:12] - [conftest.py] - INFO: Started Test: tests/subscription/test_rhsm.py::TestRhsmScaDisable::test_vdc_virtual_pool_attach_by_auto
[2023-08-09 15:12:25] - [conftest.py] - INFO: Finished Test: tests/subscription/test_rhsm.py::TestRhsmScaDisable::test_vdc_virtual_pool_attach_by_auto
```

Add the pytest_runtest_logstart&logfinish functions

---

tests/hypervisor/test_multi_hypervisors.py

Test case failed due to the error info:
```
self = <tests.hypervisor.test_multi_hypervisors.TestMultiHypervisors object at 0x7f4f32d3b490>
virtwho = <virtwho.runner.VirtwhoRunner object at 0x7f4f32d3b790>
def test_multi_hypervisors_report_together(self, virtwho):
"""Test virt-who can report multi hypervisors together
:title: virt-who: multiHypervisors: test multi hypervisors report together
:id: 9fb6694e-7535-4d9f-9ac0-75e6cbe3066d
:caseimportance: High
:tags: hypervisor,multiHypervisor
:customerscenario: false
:upstream: no
:steps:
1. Create the virt-who config files for the multi hypervisors list
2. Run the virt-who service
:expectedresults:
1. Succeed to run the virt-who, no error messages in the rhsm.log
"""
>       for mode in hypervisors_list:
E       TypeError: …
```

Fix the teat case test_multi_hypervisors_report_together

---

tests/function/test_service.py

**Descirption**
Case [test_virtwho_service_control_by_ssh_connect](https://main-jenkins-csb-virtwhoqe.apps.ocp-c1.prod.psi.redhat.com/job/regression-el8/job/function-runtest/78/testReport/junit/tests.function.test_service/TestVirtwhoService/test_virtwho_service_control_by_ssh_connect/) failed due to the error info:
```
>       assert status == "dead"
E       AssertionError: assert 'running' == 'dead'
E         - dead
E         + running
```
the ssh key from virt-who host is different in hypervisor server, remove ~/.ssh/known_hosts file in hypervisor server, works fine. We can also skip the checking.
```
[hkx303@kuhuang virtwho-test]$ pytest tests/function/test_service.py -k test_virtwho_service_control_by_ssh_connect -s
================================ test session starts …
```

Skip the strict host key checking when ssh access to virt-who server from guest

---

tests/hypervisor/test_esx.py

Fix test case [test_trigger_event_with_different_interval](https://main-jenkins-csb-virtwhoqe.apps.ocp-c1.prod.psi.redhat.com/job/regression-el8/job/hypervisor-runtest/74/testReport/junit/tests.hypervisor.test_esx/TestEsxNegative/test_trigger_event_with_different_interval/) as the result will 1 more second  than expected which is acceptable
```
[hkx303@kuhuang virtwho-test]$ pytest tests/hypervisor/test_esx.py -k test_read_only_account -s …
```

Fix test case test_trigger_event_with_different_interval

---

tests/hypervisor/test_esx.py

Add a automation test case to test ESXi available in FIPS mode.
```
================================================================== test session starts ==================================================================
platform linux -- Python 3.9.13, pytest-6.2.5, py-1.11.0, pluggy-0.13.1
rootdir: /home/jzhang/文档/test_repos/virtwho-test, configfile: pytest.ini
plugins: anyio-3.5.0, services-1.3.1, mock-1.10.4, forked-1.6.0, xdist-1.34.0
collected 30 items / 29 deselected / 1 selected                                                                                                         
tests/hypervisor/test_esx.py .                                                                                                                    [100%] …
```

[Automation] RHEL-137166 - Run virt-who in FIPS mode

---

tests/hypervisor/test_ahv.py
tests/hypervisor/test_esx.py
tests/hypervisor/test_hyperv.py
tests/hypervisor/test_kubevirt.py
tests/hypervisor/test_libvirt.py
tests/hypervisor/test_rhevm.py
tests/hypervisor/test_xen.py

test case `test_fake_type` failed due to the error info:
```
E       assert (2 == 0
E         +2
E         -0)
tests/hypervisor/test_esx.py:318: AssertionError
```
it is because the virt-who host doesn't register to the expected platform, need to fix this issue.
```
[hkx303@kuhuang virtwho-test]$ pytest tests/hypervisor/test_libvirt.py -k test_fake_type -s
collected 12 items / 11 deselected / 1 selected 
==================== 1 passed, 11 …
```

Fix the test case test_fake_type

---

tests/subscription/test_satellite.py

The testcase `test_vdc_virtual_subscription_on_webui` always failed in the automation workflow, but could be passed in the local debug, so guess it should be the network issue.
Add 5 seconds wait and run the sub-man refresh before checking the subscription.
```
% python3 -m pytest -v tests/subscription/test_satellite.py -k 'test_vdc_virtual_subscription_on_webui'
collected 11 items / 10 deselected / 1 selected …
```

Debug network issue of case test_vdc_virtual_subscription_on_webui

---

tests/subscription/test_satellite.py

Add more wait time after attach physical pool for hypervisor, the test case still failed in the jenkins job.

Debug the case failed issue for test_vdc_virtual_subscription_on_webui

---

tests/function/test_cli.py
tests/function/test_config.py

The https://bugzilla.redhat.com/show_bug.cgi?id=1996923 has been closed as won't fix, so now update the code for ahv to ignore checking the loop time around interval testing, but adding step to check another key words to make sure the virt-who can rerun after 60 seconds.
```
% python3 -m pytest --disable-warnings -v tests/function -k 'test_interval'
collected 38 items / 35 deselected / 3 selected …
```

Interval cases: update for ahv due to bz1996923 won't fix

---

tests/function/test_cli.py
tests/function/test_service.py

Update virt-who service cases with bug info

---

tests/subscription/test_satellite.py

Satellite case `test_vdc_virtual_subscription_on_webui ` always failed in the Jenkins job but could be run pass locally, which is because the guest was registered to another org in case `test_non_default_org_without_rhsm_options` and `test_non_default_org_with_rhsm_options`. 
The fix methods are
- Change to use fixture `function_guest_register`.
- Unregister guest at the final step of  `test_non_default_org_without_rhsm_options` and `test_non_default_org_with_rhsm_options`.
```
% python3 -m pytest tests/subscription/test_satellite.py -m 'tier2' -v
platform darwin -- Python 3.11.2, pytest-7.2.2, pluggy-1.0.0 -- …
```

Fix test_vdc_virtual_subscription_on_webui issue

---

virtwho/runner.py
virtwho/ssh.py

We always got much log messages in the jenkins job, most of the logs are the output after run virt-who by cli, which logs were always printed twice, one is the output of the virt-who, the other is from cat log file, so this pr added a new parameter `log_print=True` to provide us selection if the output need to be printed.
The default is also to print the log when call runcmd(), we may only need to ignore the log print after run virt-who cli, because we can see the same log in the following #cat /var/log/rhsm/rhsm.log.

Add param log_print=True to function runcmd()

---

tests/hypervisor/test_ahv.py
tests/hypervisor/test_esx.py
tests/hypervisor/test_hyperv.py
tests/hypervisor/test_kubevirt.py
tests/hypervisor/test_libvirt.py
tests/hypervisor/test_rhevm.py
tests/hypervisor/test_xen.py
tests/subscription/test_satellite.py

The case `test_vdc_temporary_pool_by_poolId` failed when second run the smoke testing job, because in this case, there was a step to `satellite.host_delete(host=hypervisor_hostname)`, but in another case `test_hypervisor_id()`, the hostname was changed to uuid or hwuuid, so there was no hostname in the satellite web when run `satellite.host_delete(host=hypervisor_hostname)`, which impacted the next steps to get temporay vdc sku, because the guest could be associated with the `uuid or hwuuid`.

Debug the virt-who smoke testing cases aginst non-released satellite

---

virtwho/register.py

The testing failed when run virt-who cases against a new Satellite, because the code was able to check if the host was registering, but not able to check if it was the correct Satellite. So now perfect to code with the checking step.

is_register(): add step to check if the correct satellite server

---

pytest.ini
tests/function/test_cli.py
tests/function/test_config.py
tests/function/test_service.py
tests/hypervisor/test_default.py
tests/hypervisor/test_esx.py
tests/subscription/test_rhsm_option.py
utils/fips_set.py
virtwho/base.py

- test_debug
- test_interval
- test_oneshot
- test_http_proxy_in_virtwho_conf
- test_virtwho_service_control_by_ssh_connect
- test_associated_info_by_rhsmlog_and_webui
- test_rhsm_proxy

Automation support the fips enable mode cases

---

tests/hypervisor/test_multi_hypervisors.py
virtwho/configure.py

Perfect the multi hypervisors case with
```
% python3 -m pytest tests/hypervisor/test_multi_hypervisors.py --disable-warnings -v
collected 1 item                                                                                                                      
tests/hypervisor/test_multi_hypervisors.py::TestMultiHypervisors::test_multi_hypervisors_report_together PASSED                 [100%] …
```

Perfect the multi hypervisors cases

---

virtwho/base.py
virtwho/provision/virtwho_hypervisor.py
virtwho/ssh.py

There was a bug when we try to check a host status by ssh_connect(), that was when the host really down, the code will directly jumped out of the ssh_connect() without returning True/False because of the line `ssh.connect(self.host, self.port, self.user, self.pwd, timeout=self.timeout)` failed in function `pwd_connect()`, which would not result step failure and told us the host was good.
The fix is to perfect the `pwd_connect(self)` to return False if the connect fail.
```
% pytest --disable-warnings -v tests/others/test_hypervisors_state.py                               
======================================================== test session starts =========================================================
platform darwin -- Python 3.11.2, pytest-7.2.2, pluggy-1.0.0 -- …
```

Perfect the ssh_connect() to support the hypervisor monitor

---

virtwho/base.py

As the discussion by meeting, we can try to test virt-who with the selinux enabled and firewall started, which should be closer to customers environments.
- Succeeded to install all the necessary packages for virt-who hosts with the new configuration.

virtwho_host: configure to start firewall and enable selinux

---

tests/others/test_hypervisors_state.py
tests/others/test_hypervisors_sw.py
tests/package/test_info.py
tests/package/test_install_uninstall.py
tests/package/test_upgrade_downgrade.py
tests/upgrade/test_upgrade.py

As the requirement for test type of Polarion cases, updated the below docstring based on https://source.redhat.com/groups/public/quality_community/quality_engineering_wiki/test_types_levels_and_importance_rev_10
- test_install_uninstall cases
:testtype: nonfunctional
:subtype1: installability
- test_upgrade_downgrade cases
:testtype: nonfunctional
:subtype1: scalability
-  test_info cases
:testtype: nonfunctional
:subtype1: documentation
- All cases in others/ have been changed to `Inactive` status because those cases are just used to test the hypervisor environments and will not be used in any test run.

docstring: add subtype1 for nonfunctional cases

---

utils/polarion_testcase_upload.py

There is the requirement to ignore all the test files under tests/others/, which could be supported by option `--collect-ignore-path` of betegeuse.
```
% python3 utils/polarion_testcase_upload.py --test-directory=tests/ --automation-script-format=https://github.com/VirtwhoQE/virtwho-test/tree/main/tests/{path} --subsystemteam=sst_subscription_virtwho --ignore-path='tests/others'       
[2024-03-06 19:12:17] - [polarion_testcase_upload.py] - INFO: 
betelgeuse test-case --automation-script-format https://github.com/VirtwhoQE/virtwho-test/tree/main/tests/{path} tests/ RHELSS temp/polarion_testcase.xml --collect-ignore-path tests/others 
[2024-03-06 19:12:19] - [polarion_testcase_upload.py] - INFO: 
[2024-03-06 19:12:19] - [polarion_testcase_upload.py] - INFO: Succeeded to …
```

polarion_testcase_upload: add to ignote test path(s)

---

utils/polarion_testrun_import.py

Following the Polarion Evidence Traceability, define the logs and fips for test run.
Have passed the test locally, the new custom fields could be uploaded successfully.

Polarion testrun: add fips and logs custom fields

---

tests/subscription/test_rhsm.py
tests/subscription/test_satellite.py

Cases under test_rhsm.py and test_satellite.py: 
- `nonfunctional:Interoperability`
- `importance:Medium` 
Because those cases are not directly testing the virt-who function, but to test the integration with entitlement server.

Update testcase importance and subtype

---

utils/satellite.py
virtwho/base.py

- Perfect the `system_init` to support set the firewall and selinux.
- Change to stop firewall for Satellite host, otherwise we cannot open the WebUI.

Stop firewall for satellite host

---

utils/satellite.py
virtwho/configure.py

Always failed with the stage account due to repo issue, so change to the product account.
Another reason is we have created new stage account for testing without so many skus attached due to entitlement mode has been ignored for testing, so the virt-who test no need to test some skus' properties.

Change to register to product rhsm for satellite deployment

---

virtwho/provision/virtwho_host.py

skip install virt-manager pakcage for rhel-10 because of not found
manually install sub-man for rhel-10 because not as default until now

rhel-10 local mode deployment support

---

virtwho/provision/virtwho_host.py

The `60s` waiting time is not enough any more before get the new added rhel guest ip address, so change to use a 30s loop to check in total 300s.

Fix local libvirt vm ip address getting issue

---

pytest.ini
tests/function/test_config.py
tests/function/test_service.py
tests/hypervisor/test_default.py
tests/hypervisor/test_esx.py
tests/package/test_info.py
tests/subscription/test_rhsm_option.py
utils/beaker.py
virtwho/provision/virtwho_host.py
virtwho/provision/virtwho_satellite.py

Got requirement from card CCT-263.
And by confirmation with Devel team, it will be nice to have some basic testing done on virt-who to catch any basic issues like this one ; may be test against a single hypervisor.
This pr helps to
- perfect beaker.py and virtwho_host.py to support install and setup fedora host for virt-who testing
- choose 7 cases as virt-who smoke test in fedora with a mark `fedoraSmoke`
**Test Result: esx+rhsm**
```
% pytest -v tests -m 'fedoraSmoke' --disable-warnings 
rootdir: …
```

Support virt-who basic testing in Fedora

---

tests/package/test_info.py

remove cases `test_version` and `test_package_info` from virt-who fedoraSmoke case library.

remove two fedoraSmoke cases

---

tests/function/test_service.py

The case `test_virtwho_service_control_by_ssh_connect case` always failed with error `"virt-who seems to be already running. If not, remove /run/virt-who.pid"`
Cause: in the last case 'test_interval' the virt-who cli keeps running, so failed to stop and start the virt-who service again by command, we should kill the pid at the begining.
```
% pytest -v --disable-warnings tests -k 'test_virtwho_service_control_by_ssh_connect'    
collected …
```

fix test_virtwho_service_control_by_ssh_connect case issue for fips test

---

utils/satellite.py

`args.rhel_compose` change to `args.distro` because the beaker installation will not only support the rhel.

maintain satellite.py due to the beaker.py updates to support fedora

---

tests/hypervisor/conftest.py
tests/hypervisor/test_ahv.py
tests/hypervisor/test_esx.py
tests/hypervisor/test_hyperv.py
tests/hypervisor/test_kubevirt.py
tests/hypervisor/test_libvirt.py
tests/subscription/conftest.py
virtwho/base.py

- test_virtwho_service_control_by_ssh_connect: fix issue to ssh connect no password
- test_rhsm_hostname： fix error message change issue with invalid value
- test_type: fix error number issue for rhel10
- test_server: fix error message change issue with invalid value
- test_username/password for hyperv: fix error message issue
```
% pytest -v --disable-warnings tests/function/test_service.py -k 'test_virtwho_service_control_by_ssh_connect' …
```

rhel10: fix case issues after run ctc1

---

tests/function/test_cli.py
tests/function/test_config.py

- add `wait=10` for the oneshot cases, because some beaker hosts are so slow that virt-who cannot get the log immediately.
- extend more` loop buffer` for interval=60s to [60, 61, 62, 63], also because some beaker hosts network issue.

fix interval and oneshot issue

---

tests/hypervisor/test_default.py

In some smoke jobs, the case `test_associated_info_by_rhsmlog_and_webui `may fail because no guest_register step before it.
Didn't find such issue in the regression test because there were many other cases before this case, so the guest must have been registered before the case.

fix test_associated_info_by_rhsmlog_and_webui case issue

---

virtwho/provision/virtwho_host.py

To fix the conflicting requests, for example
```
Error: 
Problem: cannot install both python3-3.12.2-7.el10.x86_64 from RHEL-10.0-20240623.1 and python3-3.9.18-3.el9.x86_64 from @System
- package virt-who-1.32.0-3.noarch from @commandline requires python(abi) = 3.12, but none of the providers can be installed
- package chrome-gnome-shell-42.1-1.el9.x86_64 from @System requires python(abi) = 3.9, but none of the providers can be installed
- conflicting requests
- problem with installed package chrome-gnome-shell-42.1-1.el9.x86_64
```

virtwho_host.py: yum localinstall virt-who package with --allowerasing

---

tests/function/test_cli.py
tests/function/test_config.py

When run virt-who against hyperv on fedora-40, the interval case still failed due to the loop time we got by code is `59`, which is not in the range [60, 63], so extend the range.

Fix interval case loop issue

---

tests/hypervisor/conftest.py

Virt-who failed to assert the `qemu+ssh` any more for rhel-9, so change to use the regular expression `.*` with the keyword `红帽€467aa`, which will not impact the test of rhel-10 no matter there will be the same issue in rhel-10.
Test Result
```
% pytest -v tests/hypervisor/test_libvirt.py -k 'test_server' -m 'tier2' 
collected 12 items / 11 deselected / 1 selected …
```

libvirt case test_server non-unicode assertion issue

---

virtwho/provision/virtwho_host.py

- The virt-manager issue on rhel-10 has been fixed.
- `Xorg` was not found in rhel-10, so skip it by default, we can locally install it when needed.

virtwho_host.py: update for rhel10

---

tests/package/test_info.py
virtwho/__init__.py

Update test_package_info due to RHEL-50657 was closed as not a bug, so make below changes for the version 1.31.28 and later.
- virtwho_license = "GPL-2.0-or-later AND LGPL-3.0-or-later"
- group = "Unspecified"
- remove if branch for rhel-8, the rhel8 will be run in the specified git branch
```
% pytest -v tests/package/test_info.py -k 'test_package_info' --disable-warnings
collected 6 items / 4 deselected / 2 selected …
```

test_package_info maintenance due to RHEL-50657

---

docs/virtwho_help_page_rhel_10
docs/virtwho_man_page_rhel_10
tests/function/test_service.py
tests/hypervisor/conftest.py
tests/package/test_info.py
virtwho/base.py

- test_man_page, add man page compare file
- test_help_page, add help page compare file
- test_install_uninstall_by_rpm, skip to check cert when wget download
- test_virtwho_service_control_by_ssh_connect, reset the case steps
- test_type and test_server: update the assertion for rhel-10
```
% pytest -v tests/package/test_info.py -k 'test_man_page or test_help_page' --disable-warnings  
collected 6 items / 4 deselected / 2 selected …
```

Maintain virt-who cases for rhel-10.beta

---

tests/package/test_info.py

The output of `#virt-who --verison` changes from 1.31.28
<1.31.28: virt-who 1.31.26-1.el9
>=1.31.28: virt-who 1.32.1-1.el10
```
% pytest -v --disable-warnings tests/package/test_info.py -k 'test_version'
collected 6 items / 5 deselected / 1 selected                                                                                         
tests/package/test_info.py::TestVirtwhoPackageInfo::test_version PASSED …
```

Update case test_version due to RHEL-50649/RHEL-50650 won't fix

---

virtwho/__init__.py

The `hypervisor-monitor` jobs were blocked due to a previous pr that added a new `VIRTWHO_VERSION` in __ini__, but in hypervisor-monitor job config.virtwho.package is null, which caused failure.
```
% pytest -v --disable-warnings tests/others/test_hypervisors_state.py -k 'test_state_esx'
collected 7 items / 6 deselected / 1 selected …
```

Fix VIRTWHO_VERSION issue for hypervisor-monitor

---

utils/libvirt_bridge_setup.sh

To support the new requirement test for `RHEL-53251 RFE Support IPV6 with virt-who`

Enable ipv6 address when configure local libvirt env

---

pytest.ini
tests/conftest.py
tests/function/test_cli.py
tests/function/test_config.py
tests/hypervisor/test_ahv.py
tests/hypervisor/test_default.py
tests/hypervisor/test_esx.py
tests/hypervisor/test_hyperv.py
tests/hypervisor/test_kubevirt.py
tests/hypervisor/test_libvirt.py
tests/hypervisor/test_local.py
tests/hypervisor/test_multi_hypervisors.py
tests/hypervisor/test_rhevm.py
tests/hypervisor/test_xen.py
tests/others/test_hypervisors_state.py
tests/others/test_hypervisors_sw.py
tests/package/test_info.py
tests/package/test_install_uninstall.py
tests/package/test_upgrade_downgrade.py
tests/subscription/test_rhsm.py
tests/subscription/test_rhsm_option.py
tests/subscription/test_satellite.py
virtwho/runner.py
virtwho/settings.py

Collecting small fixes here (work in progress):
- pep8
- truncate is safer than rm -rf
- explicit RHEL release skipping, no more not notRHEL9

Small fixes

---

utils/beaker.py

Card-ID: CCT-1052
the utility will stop waiting for status of a beaker job after 2hours (default value).
There is new property in virtwho.ini
[beaker]
reserve_duration=259200
timeout=7200
reserve_duration ... a time for a machine to be reservered
timeout ... the utility will stop waiting for a beaker service after timeout is lasted

CCT-1052: timeout for a beaker util

---

tests/package/test_upgrade_downgrade.py
utils/beaker.py
virtwho/__init__.py
virtwho/base.py
virtwho/provision/virtwho_host.py

card-id: CCT-1033
There are no packages to downgrade if it is the first release of the rhel distro - aka RHEL10.0, RHEL9.0, ....

a code to skip dowgrade/upgrade tests for the first release of rhel version

---

utils/beaker.py
virtwho/provision/virtwho_host.py
virtwho/ssh.py

an utility beaker.py reserves machine fips compliant when new argument '--fips' is used.
ie. there will not be any pipeline task to set machine to be fips compliant - ie. the reservered machine will be already fips compliant.
I have fixed an issue with timeout in ssh.py - a method self._connect returned bool in some cases instead of sshConnection.
I have added '--fips' argument for virtwho_host.py to prepare fips compliant machine.

fips compliant beaker reservation

---

requirements.txt
tests/conftest.py
tests/package/test_info.py
tests/package/test_upgrade_downgrade.py
utils/beaker.py
utils/beaker_types.py
virtwho/provision/virtwho_host.py
virtwho/provision/virtwho_satellite.py
virtwho/settings.py
virtwho/ssh.py

Card-ID: CCT-1269
a tool beaker.py now:
- runs all commands using subprocess (no ssh and remote machine to run commands anymore)
- can use keys provided by ssh-agent (in case no password is defined in virtwho.ini)
- uses better way to decide that a machine being reserved by beaker is ready to use
- use ssh-agent to authorize by a key the agent provides
A file  beaker_types.py added ... a few dataclasses to describe beaker report and to encapsulate a statements for beaker report

beaker util uses ssh-agent now and localhost

---

tests/function/test_config.py
tests/package/test_upgrade_downgrade.py

Card-ID: CCT-1333
sysconfig files are obsolete for RHEL9+
All those tests will be skippped in this case.

sysconfig tests will be skipped for rhel9+

---

virtwho/base.py

Card-ID: CCT-1347
a function package_install fails when beta repo are enabled.
The fix disables beta repo when installing package.

disable beta repo when installing virt-who package

---

tests/hypervisor/test_default.py
virtwho/register.py

Card-ID: CCT-1227
there is a test 'test_guest_attr_by_curl' in hypervisor/test_default.py
It uses  consumer uuid to verify that virt-who service puts guestid into candlepin.
A way to get consumer id is wrong. It is reason of failure of the test.
This PR changes a way to get consumer id.
This PR fixes the test finally.

new way to get consumer uuid

---

tests/hypervisor/test_default.py

Card-ID: CCT-1358
removed assertation of candlepin response - the previous test does the same

fix for test_associated_info_by_rhsmlog_and_webui
